-- Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    isactive BOOLEAN DEFAULT true,
	 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
select * from users;


{
    "email": "123@gmail.com",
    "isActive":true,
    "password": "123@qwer",
    "username": "sothea010"
}