-- Insert sample categories
INSERT INTO categories (name)
VALUES
  ('Drink'),
  ('Accounting and legal fees'),
  ('Bank fees'),
  ('Consultants and professional services'),
  ('Depreciation'),
  ('Employee benefits'),
  ('Employee expenses'),
  ('Entertainment'),
  ('Food'),
  ('Gifts'),
  ('Health'),
  ('Insurance'),
  ('Interest'),
  ('Learning'),
  ('Licensing fees'),
  ('Marketing'),
  ('Membership fees'),
  ('Office supplies'),
  ('Payroll'),
  ('Repairs'),
  ('Rent'),
  ('Rent or mortgage payments'),
  ('Software'),
  ('Tax'),
  ('Travel'),
  ('Utilities');